//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.17 at 12:36:40 AM CEST 
//


package entities.genericTypes;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TStatusIzmene.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TStatusIzmene">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="dodaj"/>
 *     &lt;enumeration value="brisi"/>
 *     &lt;enumeration value="menjaj"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TStatusIzmene")
@XmlEnum
public enum TStatusIzmene {

    @XmlEnumValue("dodaj")
    DODAJ("dodaj"),
    @XmlEnumValue("brisi")
    BRISI("brisi"),
    @XmlEnumValue("menjaj")
    MENJAJ("menjaj");
    private final String value;

    TStatusIzmene(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TStatusIzmene fromValue(String v) {
        for (TStatusIzmene c: TStatusIzmene.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
