//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 01:07:34 AM CEST 
//


package entities.amendment;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Pravni_osnov_donosenja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Donet_od_strane" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Postupak_donosenja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Cilj_donosenja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="vrsta" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="datum" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="mesto" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="oznaka" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pravniOsnovDonosenja",
    "donetOdStrane",
    "postupakDonosenja",
    "ciljDonosenja"
})
@XmlRootElement(name = "Sporedni_deo")
public class SporedniDeo {

    @XmlElement(name = "Pravni_osnov_donosenja")
    protected String pravniOsnovDonosenja;
    @XmlElement(name = "Donet_od_strane")
    protected String donetOdStrane;
    @XmlElement(name = "Postupak_donosenja")
    protected String postupakDonosenja;
    @XmlElement(name = "Cilj_donosenja")
    protected String ciljDonosenja;
    @XmlAttribute(name = "vrsta")
    protected String vrsta;
    @XmlAttribute(name = "datum")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlAttribute(name = "mesto")
    protected String mesto;
    @XmlAttribute(name = "oznaka")
    protected String oznaka;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the pravniOsnovDonosenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPravniOsnovDonosenja() {
        return pravniOsnovDonosenja;
    }

    /**
     * Sets the value of the pravniOsnovDonosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPravniOsnovDonosenja(String value) {
        this.pravniOsnovDonosenja = value;
    }

    /**
     * Gets the value of the donetOdStrane property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDonetOdStrane() {
        return donetOdStrane;
    }

    /**
     * Sets the value of the donetOdStrane property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDonetOdStrane(String value) {
        this.donetOdStrane = value;
    }

    /**
     * Gets the value of the postupakDonosenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostupakDonosenja() {
        return postupakDonosenja;
    }

    /**
     * Sets the value of the postupakDonosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostupakDonosenja(String value) {
        this.postupakDonosenja = value;
    }

    /**
     * Gets the value of the ciljDonosenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCiljDonosenja() {
        return ciljDonosenja;
    }

    /**
     * Sets the value of the ciljDonosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCiljDonosenja(String value) {
        this.ciljDonosenja = value;
    }

    /**
     * Gets the value of the vrsta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrsta() {
        return vrsta;
    }

    /**
     * Sets the value of the vrsta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrsta(String value) {
        this.vrsta = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the mesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMesto() {
        return mesto;
    }

    /**
     * Sets the value of the mesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMesto(String value) {
        this.mesto = value;
    }

    /**
     * Gets the value of the oznaka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOznaka() {
        return oznaka;
    }

    /**
     * Sets the value of the oznaka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOznaka(String value) {
        this.oznaka = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
